default_button: true
default_message: true
default_tab: true
default_tab_edit: true
_core:
  default_config_hash: ffjwyOkkEGJcHRBGwLlGLtdWUcTvXx8Dclcq43MZrT8
button:
  cour: true
  help: false
message:
  cour: false
  help: false
tab:
  cour: false
  help: false
tab_edit:
  cour: false
  help: false
