default_button: true
default_message: true
default_tab: true
default_tab_edit: true
_core:
  default_config_hash: ffjwyOkkEGJcHRBGwLlGLtdWUcTvXx8Dclcq43MZrT8
button:
  gawa: false
  prog: false
  cour: false
  coll: false
  spot: false
  care: false
  spag: false
  hero: false
  pgro: false
  curr: false
  bio: false
message:
  gawa: false
  prog: false
  cour: false
  coll: false
  spot: false
  care: false
  spag: false
  hero: false
  pgro: false
  curr: false
  bio: false
tab:
  gawa: false
  prog: false
  cour: false
  coll: false
  spot: false
  care: false
  spag: false
  hero: false
  pgro: false
  curr: false
  bio: false
tab_edit:
  gawa: false
  prog: false
  cour: false
  coll: false
  spot: false
  care: false
  spag: false
  hero: false
  pgro: false
  curr: false
  bio: false
