status: '1'
pattern: '[term:field_current_semester_start_dat:html_year]-[term:field_current_semester_end_date:html_year]'
php: 0
escape: 0
dependencies:
  config:
    - taxonomy.vocabulary.current_semester
