server:
  version: '2.0'
  hostname: ssotest.wvu.edu
  port: 443
  path: /cas
  verify: 0
  cert: ''
gateway:
  check_frequency: -2
  paths:
    id: request_path
    pages: ''
    negate: false
forced_login:
  enabled: false
  paths:
    id: request_path
    pages: ''
    negate: false
logout:
  logout_destination: ''
  enable_single_logout: false
  cas_logout: false
  single_logout_session_lifetime: 25
proxy:
  initialize: false
  can_be_proxied: false
  proxy_chains: ''
user_accounts:
  prevent_normal_login: true
  auto_register: true
  email_assignment_strategy: 1
  email_hostname: ''
  email_attribute: mail
  auto_assigned_roles: {  }
  restrict_password_management: true
  restrict_email_management: true
advanced:
  debug_log: false
  connection_timeout: 10
login_link_enabled: true
login_link_label: 'CAS Login'
_core:
  default_config_hash: 8DaBBGvjnTAKJrdg2aY2FHId9Qt4D2Yek7gozPUx6v8
