transport: smtp
smtp_host: email-smtp.us-east-1.amazonaws.com
smtp_port: 587
smtp_encryption: tls
smtp_credential_provider: multikey
smtp_credentials:
  multikey:
    user_password: aws_smtp_lockr
sendmail_path: /usr/sbin/sendmail
sendmail_mode: bs
spool_directory: ''
_core:
  default_config_hash: 0dJfQivKgyEp-S8D6gSRTBbpRFApE3VkpltnPMBQ5OY
